### ISSUE TITLE
修改了 exchange 后, 重启 debade-trigger, 对应的 queue 不会更新

### ISSUE THREAD

**Issue by stenote** [iamfat/debade-trigger#1]
如下第一次的配置:

``` yaml
 - exchange: YiQiKong
        type: topic
        routing_keys:
          - aa
        callback:
          url: http://path/to/api
          method: m
```

修改了配置后, 如下

``` yaml
 - exchange: Lims-CF
        type: topic
        routing_keys:
          - aa
        callback:
          url: http://path/to/api
          method: m
```

修改后重新启动 trigger, 原有的 queue 没有被删除, 依然存在, 现有显示 queue, 依然为之前错误绑定了 exchange 的queue
